default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 idle_timeout: 60
 port: 5432

development:
 <<: *default
 adapter: postgresql
 database: empower_dev
 username: user
 password: user
 host: localhost
 port: 5432

test:
 <<: *default
 adapter: postgresql
 database: empower_test
 username: user
 password: user
 host: localhost
 port: 5432